# Generated by Django 4.1.6 on 2023-02-09 23:21

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "icao_code",
                    models.CharField(
                        help_text="Airport code or location indicator is a four-letter code designating aerodromes around the world",
                        max_length=4,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
                ("country", models.CharField(help_text="Country name", max_length=100)),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
