# Generated by Django 4.1.6 on 2023-02-12 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="country",
            field=models.CharField(help_text="Country of airport", max_length=100),
        ),
        migrations.AlterField(
            model_name="airport",
            name="icao_code",
            field=models.CharField(
                help_text="Airport location indicator code designating aerodromes around the world",
                max_length=4,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
    ]
