# Generated by Django 4.1.6 on 2023-02-09 22:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("serial_number", models.CharField(max_length=36, unique=True)),
                ("manufacturer", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
