# Generated by Django 4.1.6 on 2023-02-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircrafts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="manufacturer",
            field=models.CharField(
                help_text="Aircraft manufacturer company name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="serial_number",
            field=models.CharField(
                help_text="Aircraft unique serial number", max_length=36, unique=True
            ),
        ),
    ]
